#ifndef __SHELL_SOUND_H__
#define __SHELL_SOUND_H__

#include <glib.h>

//
// PUBLIC ENUMS
//
typedef enum _WinTCShSound
{
    WINTC_SHELL_SND_ASTERISK,
    WINTC_SHELL_SND_BATTCRIT,
    WINTC_SHELL_SND_CRITSTOP,
    WINTC_SHELL_SND_CLOSEPRG,
    WINTC_SHELL_SND_DEFAULT,
    WINTC_SHELL_SND_DEVADD,
    WINTC_SHELL_SND_DEVREM,
    WINTC_SHELL_SND_DEVFAIL,
    WINTC_SHELL_SND_EXCLAM,
    WINTC_SHELL_SND_EXITWIN,
    WINTC_SHELL_SND_BATTLOW,
    WINTC_SHELL_SND_MAXIMIZE,
    WINTC_SHELL_SND_MENUCMD,
    WINTC_SHELL_SND_MENUPOP,
    WINTC_SHELL_SND_MINIMIZE,
    WINTC_SHELL_SND_NEWMAIL,
    WINTC_SHELL_SND_OPENPRG,
    WINTC_SHELL_SND_PRINTCMP,
    WINTC_SHELL_SND_PROGERR,
    WINTC_SHELL_SND_QUESTION,
    WINTC_SHELL_SND_RESTDOWN,
    WINTC_SHELL_SND_RESTUP,
    WINTC_SHELL_SND_SELECT,
    WINTC_SHELL_SND_SHOWTOOL,
    WINTC_SHELL_SND_STARTWIN,
    WINTC_SHELL_SND_SYSNOTIF,
    WINTC_SHELL_SND_LOGOFF,
    WINTC_SHELL_SND_LOGON,

    WINTC_SHELL_SND_BLKPOPUP,
    WINTC_SHELL_SND_CMPNAV,
    WINTC_SHELL_SND_EMPTYBIN,
    WINTC_SHELL_SND_INFOBAR,
    WINTC_SHELL_SND_MOVEITEM,
    WINTC_SHELL_SND_STARTNAV
} WinTCShSound;

//
// PUBLIC FUNCTIONS
//
void wintc_sh_play_sound(
    WinTCShSound sound
);

#endif
