/* This file is generated by glib-genmarshal, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */
#ifndef __WINTC_CCLOSURE_MARSHAL_MARSHAL_H__
#define __WINTC_CCLOSURE_MARSHAL_MARSHAL_H__

#include <glib-object.h>

G_BEGIN_DECLS

/* VOID:OBJECT,OBJECT,INT (marshals.list:1) */
extern
void wintc_cclosure_marshal_VOID__OBJECT_OBJECT_INT (GClosure     *closure,
                                                     GValue       *return_value,
                                                     guint         n_param_values,
                                                     const GValue *param_values,
                                                     gpointer      invocation_hint,
                                                     gpointer      marshal_data);


G_END_DECLS

#endif /* __WINTC_CCLOSURE_MARSHAL_MARSHAL_H__ */
