#ifndef __SHCOMMON_PLACES_H__
#define __SHCOMMON_PLACES_H__

#include <glib.h>

//
// PUBLIC ENUMS
//
typedef enum {
    WINTC_SH_PLACE_APPDATA,
    WINTC_SH_PLACE_DESKTOP,
    WINTC_SH_PLACE_DOWNLOADS,
    WINTC_SH_PLACE_FAVORITES,
    WINTC_SH_PLACE_DOCUMENTS,
    WINTC_SH_PLACE_MUSIC,
    WINTC_SH_PLACE_PICTURES,
    WINTC_SH_PLACE_RECENTS,
    WINTC_SH_PLACE_RECYCLEBIN,
    WINTC_SH_PLACE_VIDEO,
    WINTC_SH_PLACE_ADMINTOOLS,
    WINTC_SH_PLACE_DRIVES,
    WINTC_SH_PLACE_NETHOOD,
    WINTC_SH_PLACE_CONTROLPANEL,
    WINTC_SH_PLACE_CONNECTIONS,
    WINTC_SH_PLACE_PRINTERS
} WinTCShPlace;

//
// PUBLIC CONSTANTS
//
extern const gchar* WINTC_SH_GUID_CPL;
extern const gchar* WINTC_SH_GUID_DESKTOP;
extern const gchar* WINTC_SH_GUID_DRIVES;
extern const gchar* WINTC_SH_GUID_PRINTERS;

#endif
